import React, { useState } from 'react';
import {
  ShoppingCart,
  Plus,
  Check,
  CheckCircle2,
  Trash2,
  Share2,
  Sparkles,
  ArrowRight,
  Clock,
  IndianRupee,
  AlertTriangle,
  Send,
  Store,
  Filter,
  X,
  PackageCheck
} from 'lucide-react';
import { GroceryItem, ItemCategory, PantryItem, Recipe, StorageLocation } from '../types';
import { predictShelfLife, calculateExpiryDateString } from '../utils/expiryPredictor';

interface SmartGroceryListProps {
  groceryItems: GroceryItem[];
  pantryItems: PantryItem[];
  recipes: Recipe[];
  onToggleCheckItem: (id: string) => void;
  onAddItem: (item: Omit<GroceryItem, 'id'>) => void;
  onDeleteItem: (id: string) => void;
  onClearChecked: () => void;
  onMoveCheckedToPantry: (checkedItems: GroceryItem[]) => void;
  onGenerateSmartSuggestions: () => void;
}

export const SmartGroceryList: React.FC<SmartGroceryListProps> = ({
  groceryItems,
  pantryItems,
  recipes,
  onToggleCheckItem,
  onAddItem,
  onDeleteItem,
  onClearChecked,
  onMoveCheckedToPantry,
  onGenerateSmartSuggestions
}) => {
  const [activeGrouping, setActiveGrouping] = useState<'section' | 'urgency'>('section');
  const [urgencyFilter, setUrgencyFilter] = useState<'all' | 'urgent' | 'regular' | 'restock'>('all');
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [copiedNotification, setCopiedNotification] = useState(false);

  // Add Item Modal Form State
  const [newName, setNewName] = useState('');
  const [newQuantity, setNewQuantity] = useState('500g');
  const [newCategory, setNewCategory] = useState<ItemCategory>('vegetables');
  const [newUrgency, setNewUrgency] = useState<GroceryItem['urgency']>('regular');
  const [newSection, setNewSection] = useState<GroceryItem['storeSection']>('Sabzi Mandi');
  const [newPrice, setNewPrice] = useState<number>(30);
  const [newReason, setNewReason] = useState('');

  // Filter items
  const filteredItems = groceryItems.filter((item) => {
    if (urgencyFilter === 'all') return true;
    return item.urgency === urgencyFilter;
  });

  const checkedItems = groceryItems.filter((i) => i.checked);
  const totalEstimatedCost = filteredItems.reduce((acc, curr) => acc + (curr.checked ? 0 : curr.estimatedPrice), 0);
  const totalCartCost = groceryItems.reduce((acc, curr) => acc + curr.estimatedPrice, 0);

  // Sections list
  const STORE_SECTIONS: GroceryItem['storeSection'][] = [
    'Sabzi Mandi',
    'Dairy & Fresh',
    'Kirana & Grains',
    'Spices & Essentials',
    'Bakery & Snacks'
  ];

  const SECTION_EMOJIS: Record<GroceryItem['storeSection'], string> = {
    'Sabzi Mandi': '🥬',
    'Dairy & Fresh': '🥛',
    'Kirana & Grains': '🌾',
    'Spices & Essentials': '🌶️',
    'Bakery & Snacks': '🍞'
  };

  const handleManualAddSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newName.trim()) return;

    onAddItem({
      name: newName.trim(),
      quantity: newQuantity.trim() || '1 unit',
      category: newCategory,
      urgency: newUrgency,
      suggestedReason: newReason.trim() || 'Manual grocery addition',
      estimatedPrice: newPrice || 25,
      checked: false,
      storeSection: newSection
    });

    setIsAddModalOpen(false);
    setNewName('');
    setNewReason('');
  };

  // WhatsApp formatted string generator
  const generateWhatsAppMessage = () => {
    let msg = `🛒 *FreshTrack Smart Kirana List*\n`;
    msg += `📅 ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}\n\n`;

    STORE_SECTIONS.forEach((sec) => {
      const sectionItems = groceryItems.filter((i) => i.storeSection === sec && !i.checked);
      if (sectionItems.length > 0) {
        msg += `*${SECTION_EMOJIS[sec]} ${sec}:*\n`;
        sectionItems.forEach((it) => {
          msg += ` • ${it.name} (${it.quantity}) ~ ₹${it.estimatedPrice}\n`;
        });
        msg += `\n`;
      }
    });

    msg += `💰 *Estimated Total:* ₹${totalEstimatedCost}\n`;
    msg += `_Generated by FreshTrack AI Zero-Waste Pantry_`;

    return msg;
  };

  const handleShareWhatsApp = () => {
    const text = generateWhatsAppMessage();
    const encoded = encodeURIComponent(text);
    window.open(`https://api.whatsapp.com/send?text=${encoded}`, '_blank');
  };

  const handleCopyToClipboard = () => {
    const text = generateWhatsAppMessage();
    navigator.clipboard.writeText(text);
    setCopiedNotification(true);
    setTimeout(() => setCopiedNotification(false), 2500);
  };

  return (
    <div id="smart-grocery-list" className="space-y-6 animate-in fade-in duration-300">
      
      {/* Top Banner */}
      <div className="bg-[#046A38] text-white p-6 rounded-2xl shadow-lg border border-emerald-800 relative overflow-hidden flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="absolute -right-8 -top-8 w-44 h-44 bg-white/10 rounded-full pointer-events-none" />

        <div className="max-w-xl relative z-10">
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-500/30 text-emerald-100 border border-emerald-400/30 text-xs font-bold mb-2">
            <ShoppingCart className="w-3.5 h-3.5 text-yellow-300" /> Smart Pantry Grocery Generator
          </div>
          <h2 className="text-xl sm:text-2xl font-black tracking-tight">
            Buy Only What Your Kitchen Needs
          </h2>
          <p className="text-emerald-100/90 text-xs sm:text-sm mt-1 leading-relaxed">
            AI continuously cross-references low pantry stock with planned meals to eliminate duplicate purchases and minimize Kirana bills.
          </p>
        </div>

        {/* Action Button Controls */}
        <div className="flex flex-wrap sm:flex-nowrap gap-2 relative z-10">
          <button
            type="button"
            onClick={onGenerateSmartSuggestions}
            className="px-3.5 py-2.5 rounded-xl bg-white/15 hover:bg-white/25 text-white font-bold text-xs flex items-center gap-1.5 border border-white/20 transition-all cursor-pointer"
            title="Scan pantry for missing & low items"
          >
            <Sparkles className="w-3.5 h-3.5 text-yellow-300" />
            <span>Auto-Analyze Stock</span>
          </button>

          <button
            type="button"
            onClick={() => setIsAddModalOpen(true)}
            className="px-4 py-2.5 rounded-xl bg-yellow-400 hover:bg-yellow-300 text-emerald-950 font-black text-xs sm:text-sm flex items-center gap-1.5 shadow-md transition-all cursor-pointer whitespace-nowrap"
          >
            <Plus className="w-4 h-4" />
            <span>Add Item</span>
          </button>
        </div>
      </div>

      {/* Control Bar: Filters, Grouping, Budget Counter & WhatsApp Share */}
      <div className="bg-white p-4 rounded-2xl border border-emerald-100 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        
        {/* Urgency Filter Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto text-xs">
          {[
            { id: 'all', label: `All Items (${groceryItems.length})` },
            { id: 'urgent', label: '🔴 Urgent Needs' },
            { id: 'regular', label: '🟡 Regular Buy' },
            { id: 'restock', label: '🟢 Staples Restock' }
          ].map((pill) => (
            <button
              key={pill.id}
              type="button"
              onClick={() => setUrgencyFilter(pill.id as any)}
              className={`px-3 py-1.5 rounded-full font-bold whitespace-nowrap transition-all cursor-pointer ${
                urgencyFilter === pill.id
                  ? 'bg-emerald-700 text-white shadow-xs'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              {pill.label}
            </button>
          ))}
        </div>

        {/* Right Tools: Section/Urgency Grouping & Sharing */}
        <div className="flex flex-wrap items-center gap-2.5">
          {/* Grouping Switcher */}
          <div className="flex items-center bg-slate-100 p-1 rounded-xl text-xs font-bold text-slate-600">
            <button
              type="button"
              onClick={() => setActiveGrouping('section')}
              className={`px-2.5 py-1 rounded-lg transition-all ${
                activeGrouping === 'section' ? 'bg-white text-emerald-900 shadow-xs' : 'hover:text-slate-900'
              }`}
            >
              Store Sections
            </button>
            <button
              type="button"
              onClick={() => setActiveGrouping('urgency')}
              className={`px-2.5 py-1 rounded-lg transition-all ${
                activeGrouping === 'urgency' ? 'bg-white text-emerald-900 shadow-xs' : 'hover:text-slate-900'
              }`}
            >
              By Urgency
            </button>
          </div>

          {/* WhatsApp Share Button */}
          <button
            type="button"
            onClick={handleShareWhatsApp}
            className="px-3 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center gap-1.5 shadow-xs transition-colors cursor-pointer"
            title="Share with Cook / Family on WhatsApp"
          >
            <Send className="w-3.5 h-3.5" />
            <span>WhatsApp</span>
          </button>

          <button
            type="button"
            onClick={handleCopyToClipboard}
            className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>{copiedNotification ? 'Copied! ✓' : 'Copy'}</span>
          </button>
        </div>

      </div>

      {/* Floating Checked Bar if any items selected */}
      {checkedItems.length > 0 && (
        <div className="p-4 bg-emerald-50 border-2 border-emerald-500 rounded-2xl flex flex-col sm:flex-row items-center justify-between gap-3 text-xs animate-in slide-in-from-top-2">
          <div className="flex items-center gap-2">
            <PackageCheck className="w-5 h-5 text-emerald-700 shrink-0" />
            <div>
              <p className="font-black text-emerald-950 text-sm">
                {checkedItems.length} {checkedItems.length === 1 ? 'item' : 'items'} purchased & checked off!
              </p>
              <p className="text-emerald-800">
                Move directly into Smart Pantry with automatic Desi shelf-life expiry dates.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClearChecked}
              className="px-3 py-1.5 bg-white text-slate-600 hover:text-slate-800 font-bold rounded-lg border border-slate-200"
            >
              Clear Checked
            </button>
            <button
              id="move-checked-to-pantry-btn"
              type="button"
              onClick={() => onMoveCheckedToPantry(checkedItems)}
              className="px-4 py-2 bg-emerald-700 hover:bg-emerald-800 text-white font-black rounded-xl shadow-xs transition-all cursor-pointer flex items-center gap-1.5"
            >
              <Check className="w-4 h-4" />
              <span>Add to Smart Pantry &rarr;</span>
            </button>
          </div>
        </div>
      )}

      {/* GROCERY ITEMS DISPLAY: Grouped either by Store Section or by Urgency */}
      {activeGrouping === 'section' ? (
        <div className="space-y-6">
          {STORE_SECTIONS.map((section) => {
            const itemsInSection = filteredItems.filter((i) => i.storeSection === section);
            if (itemsInSection.length === 0) return null;

            return (
              <div key={section} className="space-y-2.5">
                <div className="flex items-center justify-between pb-1 border-b border-emerald-100">
                  <h3 className="text-sm font-black text-slate-800 flex items-center gap-2 uppercase tracking-wider">
                    <span>{SECTION_EMOJIS[section]}</span>
                    <span>{section}</span>
                    <span className="text-xs font-bold text-slate-400">({itemsInSection.length})</span>
                  </h3>
                  <span className="text-xs font-bold text-slate-500">
                    Est: ₹{itemsInSection.reduce((sum, i) => sum + i.estimatedPrice, 0)}
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {itemsInSection.map((item) => (
                    <GroceryCard
                      key={item.id}
                      item={item}
                      onToggleCheck={onToggleCheckItem}
                      onDelete={onDeleteItem}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="space-y-6">
          {(['urgent', 'regular', 'restock'] as const).map((urg) => {
            const itemsInUrgency = filteredItems.filter((i) => i.urgency === urg);
            if (itemsInUrgency.length === 0) return null;

            const labelMap = {
              urgent: '🔴 High Urgency (Tonight’s Meals / Depleted)',
              regular: '🟡 Needed This Week',
              restock: '🟢 Monthly Staple Restock'
            };

            return (
              <div key={urg} className="space-y-2.5">
                <div className="flex items-center justify-between pb-1 border-b border-emerald-100">
                  <h3 className="text-sm font-black text-slate-800 uppercase tracking-wider">
                    {labelMap[urg]} ({itemsInUrgency.length})
                  </h3>
                  <span className="text-xs font-bold text-slate-500">
                    Est: ₹{itemsInUrgency.reduce((sum, i) => sum + i.estimatedPrice, 0)}
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {itemsInUrgency.map((item) => (
                    <GroceryCard
                      key={item.id}
                      item={item}
                      onToggleCheck={onToggleCheckItem}
                      onDelete={onDeleteItem}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Empty State */}
      {filteredItems.length === 0 && (
        <div className="bg-white rounded-2xl p-12 text-center border border-slate-200">
          <ShoppingCart className="w-12 h-12 text-slate-300 mx-auto mb-3" />
          <h4 className="font-extrabold text-slate-800 text-base">Your grocery list is empty!</h4>
          <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto">
            Click &ldquo;Auto-Analyze Stock&rdquo; to automatically detect low pantry supplies or manually add an ingredient you need.
          </p>
          <div className="mt-4 flex items-center justify-center gap-2">
            <button
              type="button"
              onClick={onGenerateSmartSuggestions}
              className="px-4 py-2 bg-emerald-600 text-white font-bold text-xs rounded-xl shadow-xs"
            >
              Analyze Pantry Stock
            </button>
            <button
              type="button"
              onClick={() => setIsAddModalOpen(true)}
              className="px-4 py-2 bg-slate-100 text-slate-700 font-bold text-xs rounded-xl"
            >
              Add Item Manually
            </button>
          </div>
        </div>
      )}

      {/* Summary Footer Bar */}
      <div className="p-4 bg-white rounded-2xl border border-emerald-100 flex items-center justify-between text-xs">
        <div className="flex items-center gap-2">
          <Store className="w-4 h-4 text-emerald-700" />
          <span className="text-slate-500 font-medium">Estimated Kirana Bill:</span>
          <span className="font-black text-slate-900 text-sm">₹{totalEstimatedCost}</span>
          <span className="text-slate-400">({filteredItems.filter((i) => !i.checked).length} items remaining)</span>
        </div>

        <button
          type="button"
          onClick={handleShareWhatsApp}
          className="text-xs font-bold text-emerald-800 hover:text-emerald-950 flex items-center gap-1 cursor-pointer"
        >
          <span>Send to local Kirana / Cook</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* MANUAL ADD ITEM MODAL */}
      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-200">
          <div className="bg-white rounded-3xl max-w-md w-full shadow-2xl border border-emerald-100 overflow-hidden">
            
            <div className="p-5 bg-gradient-to-r from-emerald-800 to-[#046A38] text-white flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center text-lg border border-white/20">
                  🛒
                </div>
                <div>
                  <h3 className="text-base font-black">Add Grocery Item</h3>
                  <p className="text-xs text-emerald-100 opacity-90">Organized by Indian Kirana sections</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsAddModalOpen(false)}
                className="w-8 h-8 rounded-full bg-black/20 hover:bg-black/30 flex items-center justify-center text-white cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleManualAddSubmit} className="p-5 space-y-3.5 text-xs">
              <div>
                <label className="block font-bold text-slate-700 mb-1">Item Name *</label>
                <input
                  type="text"
                  required
                  value={newName}
                  onChange={(e) => setNewName(e.target.value)}
                  placeholder="e.g. Amul Taaza Milk, Kothmir, Toor Dal"
                  className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl font-bold focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Quantity</label>
                  <input
                    type="text"
                    value={newQuantity}
                    onChange={(e) => setNewQuantity(e.target.value)}
                    placeholder="e.g. 500g, 1 litre, 1 pkt"
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500"
                  />
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Estimated Price (₹)</label>
                  <input
                    type="number"
                    min="1"
                    value={newPrice}
                    onChange={(e) => setNewPrice(parseInt(e.target.value) || 0)}
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 font-bold"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Store Section</label>
                  <select
                    value={newSection}
                    onChange={(e) => setNewSection(e.target.value as any)}
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 font-medium"
                  >
                    <option value="Sabzi Mandi">🥬 Sabzi Mandi</option>
                    <option value="Dairy & Fresh">🥛 Dairy & Cold Storage</option>
                    <option value="Kirana & Grains">🌾 Kirana / DMart</option>
                    <option value="Spices & Essentials">🌶️ Spices & Oils</option>
                    <option value="Bakery & Snacks">🍞 Bakery & Snacks</option>
                  </select>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Urgency</label>
                  <select
                    value={newUrgency}
                    onChange={(e) => setNewUrgency(e.target.value as any)}
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 font-medium"
                  >
                    <option value="urgent">🔴 Urgent (1-2 days)</option>
                    <option value="regular">🟡 Needed This Week</option>
                    <option value="restock">🟢 Monthly Staple</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">Reason / Note (optional)</label>
                <input
                  type="text"
                  value={newReason}
                  onChange={(e) => setNewReason(e.target.value)}
                  placeholder="e.g. Needed for Palak Paneer dinner tonight"
                  className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="pt-2 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setIsAddModalOpen(false)}
                  className="px-4 py-2 font-bold text-slate-600 hover:text-slate-800"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-black rounded-xl shadow-md cursor-pointer"
                >
                  Add to List
                </button>
              </div>
            </form>

          </div>
        </div>
      )}

    </div>
  );
};

// Sub-component for individual grocery item card
const GroceryCard: React.FC<{
  item: GroceryItem;
  onToggleCheck: (id: string) => void;
  onDelete: (id: string) => void;
}> = ({ item, onToggleCheck, onDelete }) => {
  return (
    <div
      className={`p-3.5 rounded-2xl border transition-all flex items-center justify-between gap-3 ${
        item.checked
          ? 'bg-emerald-50/50 border-emerald-200 opacity-60'
          : 'bg-white border-slate-200/90 hover:border-emerald-300 shadow-2xs'
      }`}
    >
      <div className="flex items-center gap-3 min-w-0">
        <button
          type="button"
          onClick={() => onToggleCheck(item.id)}
          className={`w-6 h-6 rounded-lg flex items-center justify-center border transition-colors cursor-pointer shrink-0 ${
            item.checked
              ? 'bg-emerald-600 text-white border-emerald-600'
              : 'border-slate-300 hover:border-emerald-500 bg-slate-50'
          }`}
        >
          {item.checked && <Check className="w-4 h-4 stroke-[3]" />}
        </button>

        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h4 className={`font-bold text-xs sm:text-sm truncate ${item.checked ? 'line-through text-slate-400' : 'text-slate-900'}`}>
              {item.name}
            </h4>
            <span className="text-[10px] text-slate-500 font-medium shrink-0">
              ({item.quantity})
            </span>
          </div>

          {item.suggestedReason && (
            <p className="text-[10px] text-emerald-800 truncate font-medium mt-0.5">
              💡 {item.suggestedReason}
            </p>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2.5 shrink-0">
        <div className="text-right">
          <span className="text-xs font-black text-slate-800">
            ₹{item.estimatedPrice}
          </span>
          <div>
            <span
              className={`text-[9px] font-black uppercase px-1.5 py-0.5 rounded ${
                item.urgency === 'urgent'
                  ? 'bg-red-100 text-red-800'
                  : item.urgency === 'regular'
                  ? 'bg-amber-100 text-amber-900'
                  : 'bg-emerald-100 text-emerald-800'
              }`}
            >
              {item.urgency}
            </span>
          </div>
        </div>

        <button
          type="button"
          onClick={() => onDelete(item.id)}
          className="p-1.5 text-slate-300 hover:text-red-600 rounded-lg hover:bg-red-50 transition-colors cursor-pointer"
          title="Remove item"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
};
